### ISSUE TITLE
Directory 'node_modules' is still present in the repo

### ISSUE THREAD

**Issue by stevenventimiglia** [thakursachin467/nodejs-starter-code#2]
I would recommend editing `.gitignore`, with the following:

```
.gitignore
node_modules
```

...followed by:

```
git rm -r --cached node_modules
```
This should resolve the issue.

**Comment by thakursachin467** [comment]
Yes, I should have done it before. Thanks

**Comment by thakursachin467** [comment]
Changes made now the node_module folder is not there
